spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/fintech
    driverClassName: org.postgresql.Driver
    username: fintech
    password: fintech123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect

ledger:
  service:
    url: http://ledger-service:8081

resilience4j:
  circuitbreaker:
    instances:
      ledger-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      ledger-service:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2

logging:
  level:
    root: INFO
    com.example.transfer: DEBUG
    feign: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


