spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/fintech
    driverClassName: org.postgresql.Driver
    username: fintech
    password: fintech123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    com.example.ledger: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


