server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:ledger;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
    com.example.ledger: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
